version: '3'
services:
  mongodb:
    container_name: survey-api-mongodb
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: survey-api
    image: node:14
    working_dir: /usr/src/survey-api
    restart: always
    links:
      - mongodb
    volumes:
      - ./dist:/usr/src/survey-api/dist
      - ./package.json:/usr/src/survey-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    command: bash -c "npm install --omit=dev && npm run debug"
